# Generated by Django 3.2.9 on 2021-11-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField()),
                ('device_name', models.CharField(max_length=200)),
                ('device_room', models.CharField(max_length=200)),
                ('device_status', models.IntegerField()),
            ],
        ),
    ]
